#%RAML 1.0 DataType
displayName: Story Detail
description: 
type: object

properties:
  source:
    type: string
  author:
    type: string
  title:
    type: string
  description: 
    type: string
  url:
    type: string
  urlImage:
    type: string
  publishedDate:
    type: datetime-only
  content: 
    type: string