#%RAML 1.0 DocumentationItem
title: Notification System Service Home
content: |
  **Notification System Service** enables developers to send emails, specifying any number to TO, CC and BCC recipients, use text or html subject and body template with substituation variables, and with or without attachments.

  The consumer must preconvert any attachment data to base64 format.
